classes:
  0: person
  2: car
  3: motorcycle
  5: bus
  7: truck
  14: bird
  15: cat
  16: dog
  17: horse
  18: sheep
  19: cow

groups:
  person:
    0: person
  car:
    2: car
    3: motorcycle
    5: bus
    7: truck
  pet:
    14: bird
    15: cat
    16: dog
    17: horse
    18: sheep
    19: cow